#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := SmartHomeHub


EXTRA_COMPONENT_DIRS := FastBotLib

include $(IDF_PATH)/make/project.mk
